In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
DATA_PATH = "../data/MTA_Subway_Customer_Journey-Focused_Metrics__2020-2024.csv"
df = pd.read_csv(DATA_PATH)
df.head()

,month,division,line,period,num_passengers,additional platform time,additional train time,total_apt,total_att,over_five_mins,over_five_mins_perc,customer journey time performance
0,2020-01-01,A DIVISION,1,offpeak,7175651.0,1.881154,0.762318,13498506.0,5470124.50,876067.4,0.122089,0.877911
1,2020-01-01,A DIVISION,1,peak,7976981.5,1.612034,0.690113,12859167.0,5505022.50,901543.3,0.113018,0.886982
2,2020-01-01,A DIVISION,2,offpeak,4897338.5,1.810272,0.274704,8865514.0,1345319.40,767125.2,0.156641,0.843359
3,2020-01-01,A DIVISION,2,peak,5525236.0,1.536624,0.197920,8490208.0,1093555.80,701104.0,0.126891,0.873109
4,2020-01-01,A DIVISION,3,offpeak,3501265.8,1.547511,0.288822,5418245.5,1011241.06,403843.7,0.115342,0.884658

In [4]:
df.shape
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2856 entries, 0 to 2855
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   month                              2856 non-null   object
 1   division                           2856 non-null   object
 2   line                               2856 non-null   object
 3   period                             2856 non-null   object
 4   num_passengers                     2856 non-null   float64
 5   additional platform time           2856 non-null   float64
 6   additional train time              2856 non-null   float64
 7   total_apt                          2856 non-null   float64
 8   total_att                          2856 non-null   float64
 9   over_five_mins                     2856 non-null   float64
 10  over_five_mins_perc                2856 non-null   float64
 11  customer journey time performance  2856 non-null   float64
dtypes: float64(8), object(4)
memory usage: 267.9+ KB

In [5]:
df["month"] = pd.to_datetime(df["month"])

df["year"] = df["month"].dt.year
df["month_num"] = df["month"].dt.month

df[["month", "year", "month_num"]].head()

       month  year  month_num
0 2020-01-01  2020          1
1 2020-01-01  2020          1
2 2020-01-01  2020          1
3 2020-01-01  2020          1
4 2020-01-01  2020          1

In [6]:
df["line"] = (
    df["line"]
    .astype(str)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.upper()
)

shuttle_map = {
    "S 42ND": "S_42ND",
    "S FKLN": "S_FKLN",
    "S ROCK": "S_ROCK",
}

df["line_clean"] = df["line"].replace(shuttle_map)

sorted(df["line_clean"].unique())

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'JZ',
 'L',
 'M',
 'N',
 'Q',
 'R',
 'S_42ND',
 'S_FKLN',
 'S_ROCK',
 'W']

In [7]:
def line_type(x):
    if x.isdigit():
        return "NUMBER"
    if x.startswith("S"):
        return "SHUTTLE"
    if x == "JZ":
        return "COMBINED"
    return "LETTER"

df["line_type"] = df["line_clean"].apply(line_type)

df[["line_clean", "line_type"]].drop_duplicates().sort_values("line_clean")

   line_clean line_type
0           1    NUMBER
2           2    NUMBER
4           3    NUMBER
6           4    NUMBER
8           5    NUMBER
10          6    NUMBER
12          7    NUMBER
16          A    LETTER
18          B    LETTER
20          C    LETTER
22          D    LETTER
24          E    LETTER
26          F    LETTER
28          G    LETTER
30         JZ  COMBINED
32          L    LETTER
34          M    LETTER
36          N    LETTER
38          Q    LETTER
40          R    LETTER
14     S_42ND   SHUTTLE
42     S_FKLN   SHUTTLE
44     S_ROCK   SHUTTLE
46          W    LETTER

In [12]:
CLEAN_PATH = "../data/mta_cleaned.csv"
df.to_csv(CLEAN_PATH, index=False)